### PR TITLE
[Fix] Calculation on total

### LINKED ISSUE #120: [BUG] Incorrect calculation when switching number pad view to POS view
**Description**
Image

The calculation of the total amount appears incorrectly on the invoice creation slideout-screen when swithing between number pad view and POS view. This is confusing for a merchant when creating the invoice on a POS device.

**To Reproduce**
https://github.com/user-attachments/assets/4d810de9-8d33-4a83-87a6-41e9e927612e

1. Open the TPOS 
2. Click on Number pad icon
3. Enter amount e.g. 10 sats
4. Click POS icon
5. add items
6. Click Basket icon
7. ---> Incorrect amount is displayed on the invoice creation slideout
8. click "Pay" bar
9. ---> Correct amount is displayed on the invoice

**Expected behavior**
In step 7, the (sub)total amount should be the same

**Mobile Device**
- Android, Google Chrome
- LNbits version: Version 1.0.0rc8
- **TPOS 1.0.3**

### PR DESCRIPTION
**Pull request by talvasconcelos**
Issue comes from too much clutter and too many computed (nested) values. Also get_rates wasn't awaited which caused some issues.

Refactor some of the computed into watch.

Fixes #120

### CODE REVIEW

**Comment by dni** [comment]
unclutter it! :D i still see a lot of confusing variable names :)

**Review by motorina0 — APPROVED** [review]
LGTM

**Comment by talvasconcelos** [comment]
Taking it out of draft. Let's fix the open issue, then i'll come back for more refactor!

@dni @motorina0

File: static/js/tpos.js [hunk 1]
```diff
@@ -649,18 +665,24 @@ window.app = Vue.createApp({
...
     },
-    getRates() {
-      if (this.currency == LNBITS_DENOMINATION) {
-        this.exchangeRate = 1
+    async getRates() {
+      let rate
+      try {
+        if (this.currency == LNBITS_DENOMINATION) {
+          rate = 1
+        } else {
```
Comment (dni) [inline static/js/tpos.js:673]:
```suggestion
      let rate = 1
      try {
        if (this.currency != LNBITS_DENOMINATION) {
```

**Review by dni — APPROVED** [review]
